### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by betov75** [RomeoDespres/reapy#99]
Hi!

I'm unable to install Reapy. The PIP procedure is fine, the modules are in my only Python (3.9) site-packages folder but each time I try to run:

python -c "import reapy; reapy.configure_reaper()" from the windows command prompt while Reaper is running, I get:

C:\Users\Patrick\AppData\Local\Programs\Python\Python39\lib\site-packages\reapy\tools\network\machines.py:99: DisabledDistAPIWarning: Can't reach distant API. Please start REAPER, or call reapy.config.enable_dist_api() from inside REAPER to enable distant API.
  warnings.warn(errors.DisabledDistAPIWarning())

Both Python and the path to site-packages are inscribed in Windows PATH environment variable.

What am I doing wrong?

Thanks for all!

**Comment by betov75** [comment]
I was only adding reapy.config.enable_dist_api() instead of 
import reapy
reapy.config.enable_dist_api()

Inside Reaper's console.

**Comment by betov75** [comment]
I'm sorry, I still have the problem. Is the reapy.config.enable_dist_apit() should be relaunched each time I start Reaper? The distant API always closes access. Thanks!

**Comment by dimentorium** [comment]
Hello betov,
have you followed the steps to run the command inside reaper, to enable the distant api?
Please check here https://dimentorium.wixsite.com/raipt/post/making-reaper-ready-to-use-python-windows

You have to enable it once, and than it will work.
Make sure Python is correctly configured in Reaper and the action runs

**Comment by betov75** [comment]
Hi! Thank you very much for your help. I've been able to make it work in the python 3.9 console. It's so great, so easy. My new problem is when I try to run my script at command prompt (py reapy.py) I receive this: 

Traceback (most recent call last):
  File "C:\python\reapy.py", line 1, in <module>
    import reapy
  File "C:\python\reapy.py", line 17, in <module>
    project = reapy.Project()
AttributeError: partially initialized module 'reapy' has no attribute 'Project' (most likely due to a circular import)

All my script lines work when entered one after another in the command prompt terminal too, starting only python. (not the file)

What can it be?

Thanks a lot,
Merci beaucoup,
Patrick.

**Comment by dimentorium** [comment]
Hi betov, 
did you fix the issue with the file? You should not name your script reapy.py, as this might cause issues to the import.

**Comment by betov75** [comment]
Hi Romeo,

Everything works perfectly and it's so useful to retrieve the info I need in Python. Thanks for all that. I'm sorry about the (very) beginner python's mistake of naming my  testing python file the same as the import... At last I realized that part quite quickly. About my previous problem, it had nothing to do with your script, it's the way I installed it the first time. I have removed everything and using your advice to test, I was able to make it work very easily the second time.
Thanks again! It'll play a big part to enable blind users using midi control surfaces. I use reapy to extract some textual info and send it through tts within python.
